# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf6d0baecec320c0b62ab2722a241999bb8e29de8146bdc3905a9d36fcd2b28e5e43292cd2b6f0c9d68925a227765259fc84f4774dcce88285a25cfa689cdeb9

test:
  secret_key_base: 1057dadd9890c134a1a868c15690b4d41e1df089b10090edf09a37f63c8a3e9551f28dff291c4cb29bf6b5b020a6f09bca992f18b055bcc55d9246c3b112236d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
